steps:
  - topic: topic1
    message: Topic1 Msg
    number_of_times: 500
    sleep_between_messages: 0
    sleep_after: 0
  - topic: topic2
    message: Topic1 Msg 2
    number_of_times: 100
    sleep_between_messages: 0
    sleep_after: 0  
  - topic: topic3
    message: Topic2 Msg
    number_of_times: 700
    sleep_between_messages: 0
    sleep_after: 0
  - topic: topic4
    message: Topic2 Msg
    number_of_times: 300
    sleep_between_messages: 0
    sleep_after: 0
  - topic: topic2
    message: Topic2 Msg Yes!!
    number_of_times: 500
    sleep_between_messages: 0
    sleep_after: 0
